/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Sensor.H
**     Project   : Gasolina
**     Processor : MC9S08DZ60MLC
**     Component : BitsIO
**     Version   : Component 02.102, Driver 03.22, CPU db: 3.00.019
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 2/28/2012, 4:31 PM
**     Abstract  :
**         This bean "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This bean is set to work in Input direction only.
**     Settings  :
**         Port name                   : PTA
**
**         Bit mask of the port        : $007E
**         Number of bits/pins         : 6
**         Single bit numbers          : 0 to 5
**         Values range                : 0 to 63
**
**         Initial direction           : Input (direction cannot be changed)
**         Initial output value        : 0 = 000H
**         Initial pull option         : off
**
**         Port data register          : PTAD      [$0000]
**         Port control register       : PTADD     [$0001]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    25   |   PTA1_PIA1_ADP1_ACMP1PLUS
**                    1      |    26   |   PTA2_PIA2_ADP2_ACMP1MINUS
**                    2      |    27   |   PTA3_PIA3_ADP3_ACMP1O
**                    3      |    30   |   PTA4_PIA4_ADP4
**                    4      |    31   |   PTA5_PIA5_ADP5
**                    5      |    32   |   PTA6_PIA6_ADP6
**             ----------------------------------------------------
**
**         Optimization for            : speed
**     Contents  :
**         GetDir - bool Sensor_GetDir(void);
**         GetVal - byte Sensor_GetVal(void);
**         GetBit - bool Sensor_GetBit(byte Bit);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef Sensor_H_
#define Sensor_H_

/* MODULE Sensor. */

  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  Sensor_GetVal (component BitsIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pins and returns it
**           b) direction = Output : returns the last written value
**         Note: This bean is set to work in Input direction only.
**     Parameters  : None
**     Returns     :
**         ---        - Input value (0 to 63)
** ===================================================================
*/
byte Sensor_GetVal(void);

/*
** ===================================================================
**     Method      :  Sensor_GetBit (component BitsIO)
**
**     Description :
**         This method returns the specified bit of the input value.
**           a) direction = Input  : reads the input value from pins
**                                   and returns the specified bit
**           b) direction = Output : returns the specified bit
**                                   of the last written value
**         Note: This bean is set to work in Input direction only.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to read (0 to 5)
**     Returns     :
**         ---        - Value of the specified bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
** ===================================================================
*/
bool Sensor_GetBit(byte Bit);

/*
** ===================================================================
**     Method      :  Sensor_GetDir (component BitsIO)
**
**     Description :
**         This method returns direction of the bean.
**     Parameters  : None
**     Returns     :
**         ---        - Direction of the bean (always FALSE, Input only)
**                      FALSE = Input, TRUE = Output
** ===================================================================
*/
#define Sensor_GetDir() ( \
    (bool)0                            /* Pins are fixed to GPI mode */ \
  )



/* END Sensor. */
#endif /* #ifndef __Sensor_H_ */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.07 [04.34]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
