/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : CAN1.C
**     Project   : Gasolina
**     Processor : MC9S08DZ60MLC
**     Component : FreescaleCAN
**     Version   : Component 02.353, Driver 01.05, CPU db: 3.00.019
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 2/28/2012, 11:28 AM
**     Abstract  :
**         This bean "FreescaleCAN" implements a CAN serial channel.
**     Settings  :
**         CAN channel                 : MSCAN
**
**         Protocol
**             Interrupt priority      : 
**             Time segment 1          : 6
**             Time segment 2          : 7
**             RSJ                     : 1
**
**             Recieve accept. code    : 0x00
**             Recieve accept. mask    : 0xFFFFFFFF
**
**         Input interrupt
**             Vector name             : Vcanrx
**             Priority                : 
**
**         Output interrupt
**             Vector name             : Vcantx
**             Priority                : 
**
**     Contents  :
**         SetAcceptanceCode - byte CAN1_SetAcceptanceCode(dword AccCode1, dword AccCode2);
**         GetAcceptanceCode - void CAN1_GetAcceptanceCode(dword *AccCode1, dword *AccCode2);
**         SetAcceptanceMask - byte CAN1_SetAcceptanceMask(dword AccMask1, dword AccMask2);
**         GetAcceptanceMask - void CAN1_GetAcceptanceMask(dword *AccMask1, dword *AccMask2);
**         SetAcceptanceMode - byte CAN1_SetAcceptanceMode(byte Mode);
**         SendFrame         - byte CAN1_SendFrame(byte BufferNum, dword MessageID, byte FrameType, byte...
**         ReadFrame         - byte CAN1_ReadFrame(dword *MessageID, byte *FrameType, byte *FrameFormat,...
**         GetStateTX        - byte CAN1_GetStateTX(void);
**         GetStateRX        - bool CAN1_GetStateRX(void);
**         GetError          - byte CAN1_GetError(CAN1_TError *Err);
**         SendFrameExt      - byte CAN1_SendFrameExt(dword MessageID, byte FrameType, byte Length, byte...
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE CAN1. */

#include "CAN1.h"
#include "Sensor.h"
#include "LED.h"
#include "TI1.h"


#define CAN_STANDARD_FRAME_MAX_ID    0x07FF /* Max ID of the standard frame */
#define CAN_EXTENDED_FRAME_MAX_ID    0x1FFFFFFFUL /* Max ID of the extended frame */
#define CAN_EXTENDED_FRAME_MASK      0x60000000UL /* Invalid extended frame mask*/
#define CAN_MAX_DATA_LEN             0x08 /* Max number of data to be sent in one frame */
#define FULL_RX_BUF                  0x01 /* RX buffer full           */

#define MB_ID_IDE                    0x00080000UL
#define CAN_TX_MBUFFERS              0x03 /* Number of TX buffers */
#define CAN_MAX_RX_FIFO              0x04 /* Max length of the RX fifo */

#define CAN_STATUS_OVERRUN_MASK      0x02 /* Overrun error flag mask */
#define CAN_STATUS_TX_MASK           0x0C /* Transmitter error state mask*/
#define CAN_STATUS_RX_MASK           0x30 /* Receiver error state mask*/
#define CAN_STATUS_BOFF_MASK         0x0C /* Bus-Off state mask in register */
#define CAN_STATUS_BOFF_EXT_MASK     0x40 /* Bus-Off state mask in error flag */
#define CAN_STATUS_TX_PASS_MASK      0x08 /* Transmitter error passive state mask */
#define CAN_STATUS_RX_PASS_MASK      0x20 /* Receiver error passive state mask */
#define CAN_STATUS_TX_WARN_MASK      0x04 /* Transmitter warning mask */
#define CAN_STATUS_RX_WARN_MASK      0x10 /* Receiver warning mask */
#define CAN_STATUS_WAKEUP_MASK       0x80 /* Wakeup interrupt flag mask */

typedef struct {                       /* Message buffer structure */
          byte IDR0;
          byte IDR1;
          byte IDR2;
          byte IDR3;
          byte Data[CAN_MAX_DATA_LEN];
          byte DLR;
          byte TBPR;
          byte Reserved;
          byte Reserved2;
        }TMsgBuff;                     /* Message buffer structure */

typedef union {
          dword dw;
          struct {
            byte b0;
            byte b1;
            byte b2;
            byte b3;
          }b;
        }DwordSwap;

static volatile byte ErrFlag;          /* Error flags mirror of the status register */
static volatile byte SerFlag;          /* Internal driver flags */

/*
** ===================================================================
**     Method      :  CAN1_SetAcceptanceMode (component FreescaleCAN)
**
**     Description :
**         Sets the acceptance mode register.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Mode            - Acceptance mode.
**                           Supported modes: 
**                           TWO_32_FILTERS - Two 32-bit acceptance
**                           filters
**                           FOUR_16_FILTERS - Four 16-bit acceptance
**                           filters
**                           EIGHT_8_FILTERS - Eight 8-bit acceptance
**                           filters
**                           FILTER_CLOSED - Filter closed
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - This bean is disabled by
**                           user
**                           ERR_VALUE - Parameter has incorrect value
** ===================================================================
*/
byte CAN1_SetAcceptanceMode(byte Mode)
{
  if (Mode > 0x03) {                   /* Is mode parameter greater then 3 */
    return ERR_VALUE;                  /* If yes then error */
  }
  EnterCritical();                     /* Enter critical section */
  CANCTL0_INITRQ = 0x01;               /* Disable device */
  while(!CANCTL1_INITAK){}             /* Wait for disable */
  CANIDAC_IDAM = Mode;                 /* Set acceptance mode of the receiver */
  CANCTL0_INITRQ = 0x00;               /* Start device */
  while(CANCTL1_INITAK){}              /* Wait for enable */
  /* CANRFLG: WUPIF=1,CSCIF=1,RSTAT1=1,RSTAT0=1,TSTAT1=1,TSTAT0=1,OVRIF=1 */
  CANRFLG |= 0xFE;                     /* Reset error flags */
  /* CANRIER: WUPIE=0,CSCIE=0,RSTATE1=0,RSTATE0=0,TSTATE1=0,TSTATE0=0,OVRIE=0,RXFIE=0 */
  CANRIER = 0x00;                      /* Enable interrupts */
  ExitCritical();                      /* Exit critical section */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  CAN1_GetStateRX (component FreescaleCAN)
**
**     Description :
**         Returns a value of the reception complete flag.
**     Parameters  : None
**     Returns     :
**         ---             - The value of the receiver complete flag
**                           of the given buffer. 
**                           Possible values:
**                           FALSE - message buffer is empty
**                           TRUE - message buffer isn't empty
** ===================================================================
*/
byte CAN1_GetStateRX(void)
{
  return (byte)(((SerFlag & FULL_RX_BUF) != 0x00)? (byte)1 : (byte)0); /* Return status of the RX buffer */
}

/*
** ===================================================================
**     Method      :  CAN1_GetAcceptanceCode (component FreescaleCAN)
**
**     Description :
**         Returns a content of the acceptance code registers.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * AccCode1        - Pointer to the acceptance
**                           code for the message filtering. The
**                           acceptance code will be read from the
**                           acceptance code registers IDAR0-IDAR3.
**                           The most significant byte of the
**                           acceptance code will be read from the
**                           IDAR0 register and the least significant
**                           byte of the acceptance code will be read
**                           from the IDAR3 register.
**       * AccCode2        - Pointer to the acceptance
**                           code for the message filtering. The
**                           acceptance code will be read from the
**                           acceptance code registers IDAR4-IDAR7.
**                           The most significant byte of the
**                           acceptance code will be read from the
**                           IDAR4 register and the least significant
**                           byte of the acceptance code will be read
**                           from the IDAR7 register.
**     Returns     : Nothing
** ===================================================================
*/
void CAN1_GetAcceptanceCode(dword *AccCode1, dword *AccCode2)
{
  ((DwordSwap*)AccCode1)->b.b0 = CANIDAR0; /* Get acceptance code, register CANIDAR0 */
  ((DwordSwap*)AccCode1)->b.b1 = CANIDAR1; /* Get acceptance code, register CANIDAR1 */
  ((DwordSwap*)AccCode1)->b.b2 = CANIDAR2; /* Get acceptance code, register CANIDAR2 */
  ((DwordSwap*)AccCode1)->b.b3 = CANIDAR3; /* Get acceptance code, register CANIDAR3 */
  ((DwordSwap*)AccCode2)->b.b0 = CANIDAR4; /* Get acceptance code, register CANIDAR4 */
  ((DwordSwap*)AccCode2)->b.b1 = CANIDAR5; /* Get acceptance code, register CANIDAR5 */
  ((DwordSwap*)AccCode2)->b.b2 = CANIDAR6; /* Get acceptance code, register CANIDAR6 */
  ((DwordSwap*)AccCode2)->b.b3 = CANIDAR7; /* Get acceptance code, register CANIDAR7 */
}

/*
** ===================================================================
**     Method      :  CAN1_SetAcceptanceCode (component FreescaleCAN)
**
**     Description :
**         Sets the acceptance code registers. This method writes a
**         code mask directly to the acceptance code registers.
**     Parameters  :
**         NAME            - DESCRIPTION
**         AccCode1        - Acceptance code for the
**                           message filtering. This acceptance code
**                           will be written to the acceptance code
**                           registers IDAR0-IDAR3. The most
**                           significant byte of the acceptance code
**                           will be written to the IDAR0 register
**                           and the least significant byte of the
**                           acceptance code will be written to the
**                           IDAR3 register.
**         AccCode2        - Acceptance code for the
**                           message filtering. This acceptance code
**                           will be written to the acceptance code
**                           registers IDAR4-IDAR7. The most
**                           significant byte of the acceptance code
**                           will be written to the IDAR4 register
**                           and the least significant byte of the
**                           acceptance code will be written to the
**                           IDAR7 register.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - This bean is disabled by
**                           user
** ===================================================================
*/
byte CAN1_SetAcceptanceCode(dword AccCode1, dword AccCode2)
{
  EnterCritical();                     /* Enter critical section */
  CANCTL0_INITRQ = 0x01;               /* Disable device */
  while(!CANCTL1_INITAK){}             /* Wait for disable */
  CANIDAR3 = ((DwordSwap *)&AccCode1)->b.b3; /* Set acceptance code, register CANIDAR3 */
  CANIDAR2 = ((DwordSwap *)&AccCode1)->b.b2; /* Set acceptance code, register CANIDAR2 */
  CANIDAR1 = ((DwordSwap *)&AccCode1)->b.b1; /* Set acceptance code, register CANIDAR1 */
  CANIDAR0 = ((DwordSwap *)&AccCode1)->b.b0; /* Set acceptance code, register CANIDAR0 */
  CANIDAR7 = ((DwordSwap *)&AccCode2)->b.b3; /* Set acceptance code, register CANIDAR7 */
  CANIDAR6 = ((DwordSwap *)&AccCode2)->b.b2; /* Set acceptance code, register CANIDAR6 */
  CANIDAR5 = ((DwordSwap *)&AccCode2)->b.b1; /* Set acceptance code, register CANIDAR5 */
  CANIDAR4 = ((DwordSwap *)&AccCode2)->b.b0; /* Set acceptance code, register CANIDAR4 */
  CANCTL0_INITRQ = 0x00;               /* Start device */
  while(CANCTL1_INITAK){}              /* Wait for enable */
  /* CANRFLG: WUPIF=1,CSCIF=1,RSTAT1=1,RSTAT0=1,TSTAT1=1,TSTAT0=1,OVRIF=1 */
  CANRFLG |= 0xFE;                     /* Reset error flags */
  /* CANRIER: WUPIE=0,CSCIE=0,RSTATE1=0,RSTATE0=0,TSTATE1=0,TSTATE0=0,OVRIE=0,RXFIE=0 */
  CANRIER = 0x00;                      /* Enable interrupts */
  ExitCritical();                      /* Exit critical section */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  CAN1_GetError (component FreescaleCAN)
**
**     Description :
**         Returns the content of the receiver flag register.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Err             - Pointer to the returned set of errors
**     Returns     :
**         ---             - Error code (if GetError did not succeed),
**                           possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte CAN1_GetError(CAN1_TError *Err)
{
  Err->err = 0x00;                     /* Clear all errors */
  Err->errName.BusOff = ((ErrFlag & CAN_STATUS_BOFF_EXT_MASK) == CAN_STATUS_BOFF_EXT_MASK); /* Bus-Off state */
  Err->errName.TxWarning = ((ErrFlag & CAN_STATUS_TX_WARN_MASK) == CAN_STATUS_TX_WARN_MASK); /* Transmitter warning */
  Err->errName.RxWarning = ((ErrFlag & CAN_STATUS_RX_WARN_MASK) == CAN_STATUS_RX_WARN_MASK); /* Receiver warning */
  Err->errName.RxPassive = ((ErrFlag & CAN_STATUS_RX_PASS_MASK) == CAN_STATUS_RX_PASS_MASK); /* Receiver Error passive state */
  Err->errName.TxPassive = ((ErrFlag & CAN_STATUS_TX_PASS_MASK) == CAN_STATUS_TX_PASS_MASK); /* Transmitter Error passive state */
  Err->errName.OverRun = ((ErrFlag & CAN_STATUS_OVERRUN_MASK) == CAN_STATUS_OVERRUN_MASK); /* Overrun error flag */
  ErrFlag = 0x00;                      /* Clear error flags */
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  CAN1_GetAcceptanceMask (component FreescaleCAN)
**
**     Description :
**         Returns the content of acceptance mask registers.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * AccMask1        - Pointer to the acceptance
**                           mask for the message filtering. The
**                           acceptance mask will be read from the
**                           acceptance mask registers IDMR0-IDMR3.
**                           The most significant byte of the
**                           acceptance mask will be read from the
**                           IDMR0 register and the least significant
**                           byte of the acceptance mask will be read
**                           from the IDMR3 register.
**       * AccMask2        - Pointer to the acceptance
**                           mask for the message filtering. The
**                           acceptance mask will be read from the
**                           acceptance mask registers IDMR4-IDMR7.
**                           The most significant byte of the
**                           acceptance mask will be read from the
**                           IDMR4 register and the least significant
**                           byte of the acceptance mask will be read
**                           from the IDMR7 register.
**     Returns     : Nothing
** ===================================================================
*/
void CAN1_GetAcceptanceMask(dword *AccMask1, dword *AccMask2)
{
  ((DwordSwap *)AccMask1)->b.b0 = CANIDMR0; /* Get acceptance mask, register CANIDMR0 */
  ((DwordSwap *)AccMask1)->b.b1 = CANIDMR1; /* Get acceptance mask, register CANIDMR1 */
  ((DwordSwap *)AccMask1)->b.b2 = CANIDMR2; /* Get acceptance mask, register CANIDMR2 */
  ((DwordSwap *)AccMask1)->b.b3 = CANIDMR3; /* Get acceptance mask, register CANIDMR3 */
  ((DwordSwap *)AccMask2)->b.b0 = CANIDMR4; /* Get acceptance mask, register CANIDMR4 */
  ((DwordSwap *)AccMask2)->b.b1 = CANIDMR5; /* Get acceptance mask, register CANIDMR5 */
  ((DwordSwap *)AccMask2)->b.b2 = CANIDMR6; /* Get acceptance mask, register CANIDMR6 */
  ((DwordSwap *)AccMask2)->b.b3 = CANIDMR7; /* Get acceptance mask, register CANIDMR7 */
}

/*
** ===================================================================
**     Method      :  CAN1_SendFrame (component FreescaleCAN)
**
**     Description :
**         Sends the frame via the CAN device. Using this method the
**         user can send own message to the CAN bus. This method
**         allows to specify CAN buffer number, message ID, data to
**         be sent and frame type (DATA_FRAME/REMOTE_FRAME).
**     Parameters  :
**         NAME            - DESCRIPTION
**         BufferNum       - Number of the buffer.
**         MessageID       - Identification of the
**                           message - ID. Message ID can be
**                           specified in the STANDARD format
**                           (default) or the EXTENDED format. The
**                           most significant bit in the ID is set to
**                           specify EXTENDED format. Predefined
**                           macro CAN_EXTENDED_FRAME_ID can be used
**                           (ID "bitwise or" CAN_EXTENDED_FRAME_ID)
**                           to mark ID as extended. If the most
**                           significant bit of ID is clear, STANDARD
**                           format is used.
**         FrameType       - Type of frame
**                           DATA_FRAME - data frame
**                           REMOTE_FRAME - remote frame
**         Length          - The length of the frame in bytes
**                           (0..8)
**       * Data            - Pointer to data
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - This bean is disabled by
**                           user
**                           ERR_VALUE - Some parameter is out of
**                           possible range
**                           ERR_TXFULL - Transmition buffer is full.
** ===================================================================
*/
byte CAN1_SendFrame(byte BufferNum,dword MessageID,byte FrameType,byte Length,byte *Data)
{
  byte i;                              /* Temporary variables */
  byte bufmask = (byte)((word)1 << BufferNum); /* Buffer mask */
  TMsgBuff *MsgBuff;
  dword tmpId;

  if (((MessageID & CAN_EXTENDED_FRAME_ID) == 0) && (MessageID > CAN_STANDARD_FRAME_MAX_ID)) { /* Is the standard ID greater that 2047? */
    return ERR_VALUE;                  /* If yes then error */
  }
  if (((MessageID & CAN_EXTENDED_FRAME_ID) == CAN_EXTENDED_FRAME_ID) && (MessageID & CAN_EXTENDED_FRAME_MASK)) { /* Is the extended ID greater that 536870911? */
    return ERR_VALUE;                  /* If yes then error */
  }
  if ((BufferNum > (CAN_TX_MBUFFERS - 1)) || (Length > CAN_MAX_DATA_LEN)) { /* Is BufferNum greater than CAN_MAXBUFF or Length greater than CAN_MAX_DATA_LEN? */
    return ERR_VALUE;                  /* If yes then error */
  }
  if (FrameType > REMOTE_FRAME) {      /* Is FrameType other than REMOTE_FRAME or DATA_FRAME */
    return ERR_VALUE;                  /* If yes then error */
  }
  EnterCritical();                     /* Disable global interrupts */
  if (!(CANTFLG & bufmask)) {          /* Is the transmit buffer full? */
    ExitCritical();                    /* Enable global interrupts */
    return ERR_TXFULL;                 /* If yes then error */
  }
  CANTBSEL = bufmask;                  /* Select requested transmit buffer */
  MsgBuff = (TMsgBuff *)&CANTIDR0;
  if (MessageID & CAN_EXTENDED_FRAME_ID) {
    tmpId = (((MessageID & 0x1FFC0000UL) << 3) | 0x00180000UL | ((MessageID & 0x0003FFFFUL) << 1)); /* Extended frame */
  }
  else {
    tmpId = MessageID << 21;           /* Standard frame */
  }
  MsgBuff->IDR3 = ((DwordSwap *)&tmpId)->b.b3; /* Store the message ID */
  MsgBuff->IDR2 = ((DwordSwap *)&tmpId)->b.b2;
  MsgBuff->IDR1 = ((DwordSwap *)&tmpId)->b.b1;
  MsgBuff->IDR0 = ((DwordSwap *)&tmpId)->b.b0;
  if (FrameType == DATA_FRAME) {       /* Is it a data frame? */
    for (i=0; i<Length; i++) {
      MsgBuff->Data[i] = Data[i];      /* Store data to the transmit register */
    }
    if (MessageID & CAN_EXTENDED_FRAME_ID) { /* Is it the extended frame? */
      MsgBuff->IDR3 &= 0xFE;           /* If no then set message type as "data frame" */
    }
    else {
      MsgBuff->IDR1 &= 0xEF;           /* If yes then set message type as "data frame" */
    }
  }
  else {                               /* Remote frame */
    if (MessageID & CAN_EXTENDED_FRAME_ID) { /* Is it the extended frame? */
      MsgBuff->IDR3 |= 0x01;           /* If yes then set message type as "remote frame" */
    }
    else {
      MsgBuff->IDR1 |= 0x10;           /* If yes then set message type as "remote frame" */
    }
  }
  MsgBuff->DLR = Length;               /* Set the length of the message */
  MsgBuff->TBPR = 0x00;                /* Set the priority (high) */
  CANTFLG = bufmask;                   /* Start transmission */
  ExitCritical();                      /* Enable global interrupts */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  CAN1_SendFrameExt (component FreescaleCAN)
**
**     Description :
**         Sends a frame. This method automatically selects a free
**         transmit buffer for data transmission. The user cannot
**         specify a transmit buffer.
**     Parameters  :
**         NAME            - DESCRIPTION
**         MessageID       - Identification of the
**                           message - ID. Message ID can be
**                           specified in the STANDARD format
**                           (default) or the EXTENDED format. The
**                           most significant bit in the ID is set to
**                           specify EXTENDED format. Predefined
**                           macro CAN_EXTENDED_FRAME_ID can be used
**                           (ID "bitwise or" CAN_EXTENDED_FRAME_ID)
**                           to mark ID as extended. If the most
**                           significant bit of ID is clear, STANDARD
**                           format is used.
**         FrameType       - Type of frame
**                           DATA_FRAME - data frame
**                           REMOTE_FRAME - remote frame
**         Length          - The length of the frame in bytes
**                           (0..8)
**       * Data            - Pointer to data
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - This bean is disabled by
**                           user
**                           ERR_VALUE - Some parameter is out of
**                           possible range
** ===================================================================
*/
byte CAN1_SendFrameExt(dword MessageID,byte FrameType,byte Length,byte *Data)
{
  byte i;                              /* Temporary variables */
  TMsgBuff *MsgBuff;
  dword tmpId;

  if (((MessageID & CAN_EXTENDED_FRAME_ID) == 0) && (MessageID > CAN_STANDARD_FRAME_MAX_ID)) { /* Is the standard ID greater that 2047? */
    return ERR_VALUE;                  /* If yes then error */
  }
  if (((MessageID & CAN_EXTENDED_FRAME_ID) == CAN_EXTENDED_FRAME_ID) && (MessageID & CAN_EXTENDED_FRAME_MASK)) { /* Is the extended ID greater that 536870911? */
    return ERR_VALUE;                  /* If yes then error */
  }
  if (Length > CAN_MAX_DATA_LEN) {     /* Is the message length greater than 8?*/
    return ERR_VALUE;                  /* If yes then error */
  }
  if (FrameType > REMOTE_FRAME) {      /* Is FrameType other than REMOTE_FRAME or DATA_FRAME */
    return ERR_VALUE;                  /* If yes then error */
  }
  EnterCritical();                     /* Disable global interrupts */
  if (!(CANTFLG & 0x07)) {             /* Are all transmit buffers full? */
    ExitCritical();                    /* Enable global interrupts */
    return ERR_TXFULL;                 /* If yes then error */
  }
  CANTBSEL = CANTFLG;                  /* Find any empty transmit buffer */
  MsgBuff = (TMsgBuff *)&CANTIDR0;
  if (MessageID & CAN_EXTENDED_FRAME_ID) {
    tmpId = (((MessageID & 0x1FFC0000UL) << 3) | 0x00180000UL | ((MessageID & 0x0003FFFFUL) << 1)); /* Extended frame */
  }
  else {
    tmpId = MessageID << 21;           /* Standard frame */
  }
  MsgBuff->IDR3 = ((DwordSwap *)&tmpId)->b.b3; /* Store the message ID */
  MsgBuff->IDR2 = ((DwordSwap *)&tmpId)->b.b2;
  MsgBuff->IDR1 = ((DwordSwap *)&tmpId)->b.b1;
  MsgBuff->IDR0 = ((DwordSwap *)&tmpId)->b.b0;
  if (FrameType == DATA_FRAME) {       /* Is it a data frame? */
    for (i=0; i<Length; i++) {
      MsgBuff->Data[i] = Data[i];      /* Store data to the transmit register */
    }
    if (MessageID & CAN_EXTENDED_FRAME_ID) { /* Is it the extended frame? */
      MsgBuff->IDR3 &= 0xFE;           /* If no then set message type as "data frame" */
    }
    else {
      MsgBuff->IDR1 &= 0xEF;           /* If yes then set message type as "data frame" */
    }
  }
  else {                               /* Remote frame */
    if (MessageID & CAN_EXTENDED_FRAME_ID) { /* Is it the extended frame? */
      MsgBuff->IDR3 |= 0x01;           /* If yes then set message type as "remote frame" */
    }
    else {
      MsgBuff->IDR1 |= 0x10;           /* If yes then set message type as "remote frame" */
    }
  }
  CANTDLR = Length;                    /* Set the length of the message */
  CANTTBPR = 0x00;                     /* Set the priority (high) */
  CANTFLG = CANTBSEL;                  /* Start transmission */
  ExitCritical();                      /* Enable global interrupts */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  CAN1_ReadFrame (component FreescaleCAN)
**
**     Description :
**         Reads a frame from the CAN device. The user is informed
**         about CAN reception through OnFullRxBuffer event or
**         GetStateRX method.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * MessageID       - Pointer to a message
**                           indentification
**       * FrameType       - Pointer to a frame type
**                           DATA_FRAME - data frame
**                           REMOTE_FRAME - remote frame
**       * FrameFormat     - Pointer to a frame
**                           format
**                           STANDARD_FORMAT - standard frame 11-bits
**                           EXTENDED_FORMAT - extended frame 29-bits.
**                           Note: This parameter is obsolete and
**                           will be removed in future releases.
**       * Length          - Pointer to a length of the frame
**       * Data            - The buffer for received data
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - This bean is disabled by
**                           user
**                           ERR_RXEMPTY - The receive buffer is
**                           empty
**                           ERR_OVERRUN - The previous (unread)
**                           message in the receive buffer was
**                           overwriten by a new message. Returns
**                           only if Interrupt service is enabled.
** ===================================================================
*/
byte CAN1_ReadFrame(dword *MessageID,byte *FrameType,byte *FrameFormat,byte *Length,byte *Data)
{
  byte i;
  dword tmpId = 0;

  if (!(SerFlag & FULL_RX_BUF)) {      /* Is the receive buffer empty? */
    return ERR_RXEMPTY;                /* If yes then error */
  }
  ((DwordSwap*)&tmpId)->b.b0 = CANRIDR0;
  ((DwordSwap*)&tmpId)->b.b1 = CANRIDR1;
  ((DwordSwap*)&tmpId)->b.b2 = CANRIDR2;
  ((DwordSwap*)&tmpId)->b.b3 = CANRIDR3;
  if (tmpId & MB_ID_IDE) {
    *MessageID = ((tmpId >> 1) & 0x3FFFFUL) | ((tmpId >> 3) & 0x1FFC0000UL) | CAN_EXTENDED_FRAME_ID; /* Extended frame */
  }
  else {
    *MessageID = tmpId >> 21;          /* Standard frame */
  }
  if (*MessageID & CAN_EXTENDED_FRAME_ID) {
    *FrameFormat = EXTENDED_FORMAT;
    *FrameType = (byte)((CANRIDR3 & 0x01)? (byte)REMOTE_FRAME : (byte)DATA_FRAME); /* Result the frame type */
    *MessageID &= ~CAN_EXTENDED_FRAME_ID; /* Remove EXTENDED_FRAME indicator, frame type will be returned in FrameType parameter */
  }
  else {
    *FrameFormat = STANDARD_FORMAT;
    *FrameType = (byte)((CANRIDR1 & 0x10)? (byte)REMOTE_FRAME : (byte)DATA_FRAME); /* Result the frame type */
  }
  *Length = (byte)(CANRDLR & 0x0F);    /* Result length of the message */
  if (*FrameType == DATA_FRAME) {      /* Is it "data frame"? */
    for (i=0; i<*Length; i++) {
      Data[i] = *((byte *)&CANRDSR0 + i); /* Return received data */
    }
  }
  SerFlag &= ~FULL_RX_BUF;             /* Clear flag "full RX buffer" */
  if (SerFlag & CANRFLG_OVRIF_MASK) {  /* Is the overrun detected? */
    SerFlag &= ~CANRFLG_OVRIF_MASK;    /* Clear the internal overrun flag */
    return ERR_OVERRUN;                /* If yes then error */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  CAN1_Init (component FreescaleCAN)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void CAN1_Init(void)
{
  /* CANCTL1: CANE=1,CLKSRC=0,LOOPB=0,LISTEN=0,BORM=0,WUPM=0,SLPAK=0,INITAK=0 */
  CANCTL1 = 0x80;                      /* Set the control register */
  /* CANCTL0: RXFRM=0,RXACT=0,CSWAI=0,SYNCH=0,TIME=0,WUPE=0,SLPRQ=0,INITRQ=1 */
  CANCTL0 = 0x01;                      /* Set the control register */
  CANIDAC_IDAM = 0x00;                 /* Set the acceptance mode */
  CANIDAR0 = 0x00;                     /* Set the acceptance code, register CANIDAR0 */
  CANIDAR1 = 0x00;                     /* Set the acceptance code, register CANIDAR1 */
  CANIDAR2 = 0x00;                     /* Set the acceptance code, register CANIDAR2 */
  CANIDAR3 = 0x00;                     /* Set the acceptance code, register CANIDAR3 */
  CANIDAR4 = 0x00;                     /* Set the acceptance code, register CANIDAR4 */
  CANIDAR5 = 0x00;                     /* Set the acceptance code, register CANIDAR5 */
  CANIDAR6 = 0x00;                     /* Set the acceptance code, register CANIDAR6 */
  CANIDAR7 = 0x00;                     /* Set the acceptance code, register CANIDAR7 */
  CANIDMR0 = 0xFF;                     /* Set the acceptance mask, register CANIDMR0 */
  CANIDMR1 = 0xFF;                     /* Set the acceptance mask, register CANIDMR1 */
  CANIDMR2 = 0xFF;                     /* Set the acceptance mask, register CANIDMR2 */
  CANIDMR3 = 0xFF;                     /* Set the acceptance mask, register CANIDMR3 */
  CANIDMR4 = 0xFF;                     /* Set the acceptance mask, register CANIDMR4 */
  CANIDMR5 = 0xFF;                     /* Set the acceptance mask, register CANIDMR5 */
  CANIDMR6 = 0xFF;                     /* Set the acceptance mask, register CANIDMR6 */
  CANIDMR7 = 0xFF;                     /* Set the acceptance mask, register CANIDMR7 */
  /* CANBTR0: SJW1=0,SJW0=1,BRP5=0,BRP4=0,BRP3=0,BRP2=1,BRP1=1,BRP0=1 */
  CANBTR0 = 0x47;                      /* Set the device timing register */
  /* CANBTR1: SAMP=0,TSEG22=1,TSEG21=1,TSEG20=1,TSEG13=0,TSEG12=1,TSEG11=1,TSEG10=0 */
  CANBTR1 = 0x76;                      /* Set the device timing register */
  CANCTL1_CLKSRC = 0x01;               /* Select the clock source from bus clock */
  CANCTL0_INITRQ = 0x00;               /* Start device */
  while(CANCTL1_INITAK) {}             /* Wait for enable */
  /* CANRFLG: WUPIF=1,CSCIF=1,RSTAT1=1,RSTAT0=1,TSTAT1=1,TSTAT0=1,OVRIF=1 */
  CANRFLG |= 0xFE;                     /* Reset error flags */
  /* CANRIER: WUPIE=0,CSCIE=0,RSTATE1=0,RSTATE0=0,TSTATE1=0,TSTATE0=0,OVRIE=0,RXFIE=0 */
  CANRIER = 0x00;                      /* Enable interrupts */
}

/*
** ===================================================================
**     Method      :  CAN1_GetStateTX (component FreescaleCAN)
**
**     Description :
**         Returns a value of the transmission complete flags.
**     Parameters  : None
**     Returns     :
**         ---             - Content of the transmitter complete
**                           flag register.
** ===================================================================
*/
/*
byte CAN1_GetStateTX(void)

**      This method is implemented as a macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  CAN1_SetAcceptanceMask (component FreescaleCAN)
**
**     Description :
**         Sets the acceptance mask registers. This method writes an
**         acceptance mask directly to the acceptance mask registers.
**     Parameters  :
**         NAME            - DESCRIPTION
**         AccMask1        - Acceptance mask for the
**                           message filtering. This acceptance mask
**                           will be written to the acceptance mask
**                           registers IDMR0-IDMR3. The most
**                           significant byte of the acceptance mask
**                           will be written to the IDMR0 register
**                           and the least significant byte of the
**                           acceptance mask will be written to the
**                           IDMR3 register.
**         AccMask2        - Acceptance mask for the
**                           message filtering. This acceptance mask
**                           will be written to the acceptance mask
**                           registers IDMR4-IDMR7. The most
**                           significant byte of the acceptance mask
**                           will be written to the IDMR4 register
**                           and the least significant byte of the
**                           acceptance mask will be written to the
**                           IDMR7 register.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - This bean is disabled by
**                           user
** ===================================================================
*/
byte CAN1_SetAcceptanceMask(dword AccMask1, dword AccMask2)
{
  EnterCritical();                     /* Enter critical section */
  CANCTL0_INITRQ = 0x01;               /* Disable device */
  while(!CANCTL1_INITAK){}             /* Wait for disable */
  CANIDMR3 = ((DwordSwap *)&AccMask1)->b.b3; /* Set acceptance mask, register CANIDMR3 */
  CANIDMR2 = ((DwordSwap *)&AccMask1)->b.b2; /* Set acceptance mask, register CANIDMR2 */
  CANIDMR1 = ((DwordSwap *)&AccMask1)->b.b1; /* Set acceptance mask, register CANIDMR1 */
  CANIDMR0 = ((DwordSwap *)&AccMask1)->b.b0; /* Set acceptance mask, register CANIDMR0 */
  CANIDMR7 = ((DwordSwap *)&AccMask2)->b.b3; /* Set acceptance mask, register CANIDMR7 */
  CANIDMR6 = ((DwordSwap *)&AccMask2)->b.b2; /* Set acceptance mask, register CANIDMR6 */
  CANIDMR5 = ((DwordSwap *)&AccMask2)->b.b1; /* Set acceptance mask, register CANIDMR5 */
  CANIDMR4 = ((DwordSwap *)&AccMask2)->b.b0; /* Set acceptance mask, register CANIDMR4 */
  CANCTL0_INITRQ = 0x00;               /* Start device */
  while(CANCTL1_INITAK) {}             /* Wait for device initialization acknowledge */
  /* CANRFLG: WUPIF=1,CSCIF=1,OVRIF=1 */
  CANRFLG |= 0xC2;                     /* Reset error flags */
  /* CANRIER: WUPIE=0,CSCIE=0,RSTATE1=0,RSTATE0=0,TSTATE1=0,TSTATE0=0,OVRIE=0,RXFIE=0 */
  CANRIER = 0x00;                      /* Enable interrupts */
  ExitCritical();                      /* Exit critical section */
  return ERR_OK;                       /* OK */
}


/*
** ===================================================================
**     Method      :  CAN1_InterruptRx (component FreescaleCAN)
**
**     Description :
**         The method services the receive interrupt of the selected 
**         peripheral(s) and eventually invokes the beans event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define ON_OVERRUN  1
ISR(CAN1_InterruptRx)
{
  if (SerFlag & FULL_RX_BUF) {         /* Is any char already present in the receive buffer? */
    SerFlag |= CAN_STATUS_OVERRUN_MASK; /* If yes then set internal flag OVERRUN */
  }
  SerFlag |= FULL_RX_BUF;              /* Set flag "full RX buffer" */
  ErrFlag |= (SerFlag & 0x83);         /* Add new error flags into the ErrorFlag status variable */
  CANRFLG = CANRFLG_RXF_MASK;          /* Reset the reception complete flag and release the RX buffer */
}

/*
** ===================================================================
**     Method      :  CAN1_InterruptError (component FreescaleCAN)
**
**     Description :
**         The method services the error interrupt of the selected 
**         peripheral(s) and eventually invokes the beans event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CAN1_InterruptError)
{
  byte Status = CANRFLG;               /* Read the status register */

  if((Status & CAN_STATUS_BOFF_MASK) == CAN_STATUS_BOFF_MASK) { /* Bus-Off state */
    ErrFlag |= CAN_STATUS_BOFF_EXT_MASK;
    ErrFlag |= (Status & 0x83);        /* Add error flags */
  }
  else {
    ErrFlag |= (Status & 0xBF);        /* Add error flags */
  }
  CANRFLG = 0xFE;                      /* Reset error flags */
}


/* END CAN1. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.07 [04.34]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
